# Site settings
title: Vindo
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vindo-app.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
