# Site settings

email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vindo.co" # the base hostname & protocol for your site
repository: "vindo-app/vindo-app.github.io"
download_url: "https://github.com/vindo-app/vindo/releases/download/1.0/vindo-1.0.zip"

title: "Vindo: Run Windows Programs. On Mac."
description: "Vindo can run tons of cool Windows programs and games on a Mac, with just a simple double-click."

collections:
    versions:
    compatibility:
        output: true
        permalink: "/compatibility/:path.html"
    
defaults:
    - scope:
        type: posts
      values:
        permalink: "/blog/:title/"
    - scope: 
        path: ""
      values:
        layout: default
    - scope:
        path: ""
        type: compatibility
      values:
        layout: compat

# Build settings
markdown: kramdown

prose:
    date: CURRENT_DATETIME
    siteurl: "https://vindo.co/"
    media: images
    ignore:
        - /_data
        - /_includes
        - /_layouts
        - /_sass
        - /_versions
        - /css
        - /vanillabox
        - .codio
        - CNAME
        - bak
        - sitemap.xml
        - appcast.xml
        - _config.yml
        - .gitignore
    metadata:
        _posts:
            - name: title
              field:
                  element: text
                  label: "Title"
            - name: "published"
              field:
                  element: "checkbox"
                  label: "Published"
                  value: false
            - name: type
              field:
                  element: hidden
                  value: post
            - name: author
              field:
                  element: select
                  label: "Author"
                  options: 
                      - name: "Theodore"
                        value: "Theodore"
                      - name: "Joseph"
                        value: "Joseph"
                  
