# Site settings

email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vindo.co" # the base hostname & protocol for your site

title: "Vindo: Run Windows Programs. On Mac."
description: "Run Windows Programs. On Mac."

collections:
    - versions
    
defaults:
    - scope: 
        path: ""
      values:
        layout: default

# Build settings
markdown: kramdown
