# Site settings

email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vindo.co" # the base hostname & protocol for your site

title: "Vindo: Run Windows Programs. On Mac."
description: "Run Windows Programs. On Mac."

collections:
    - versions
    
defaults:
    - scope: 
        path: ""
      values:
        layout: default

# Build settings
markdown: kramdown

prose:
    date: CURRENT_DATETIME
    siteurl: "https://vindo.co/"
    media: images
    ignore:
        - /_data
        - /_includes
        - /_sass
        - /_versions
        - /css
        - /vanillabox
        - .codio
        - CNAME
        - bak
        - sitemap.xml
        - appcast.xml
    metadata:
        _posts:
            - name: title
              field:
                  element: text
                  label: "Title"
            - name: "published"
              field:
                  element: "checkbox"
                  label: "Published"
                  value: false
            - name: type
              field:
                  element: hidden
                  value: post
            - name: author
              field:
                  element: select
                  label: "Author"
                  options: 
                      - name: "Theodore"
                        value: "Theodore"
                      - name: "Joseph"
                        value: "Joseph"
                  